modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
    modId="emomod"
    version="${file.jarVersion}"
    displayName="Emotion's Mod"
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
    logoFile="ModEmotion.png" #optional
    credits="Thanks MinecraftForgeFrance and MinecraftForge forum for the help" #optional
    authors="EmotionFox" #optional
    description='''
Emotion's Mod is a huge mod with many additions of gameplay features, biomes, blocks, items, features etc.. The main focus was to stay "vanillia proof" in the textures and implementations, to add variation and extends the lifetime of the soft.

He was created by default to be played with my girlfriend EmotionKitten and friend EmotionBest, but since you can have it I've certainly put it online so, ENJOY :)
    '''

[[dependencies.emomod]] #optional
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.emomod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
